APPENV="dev"

[log]
format="json"
level="info"
noColor="no_color"

[app]
httpaddr=4000

[database]
host="localhost"
port=3306
user="viigstar"
pass="12345678"
name="dev"

[psql]
host="172.20.0.4"
port=5432
user="postgres"
pass="your-super-secret-and-long-postgres-password"
name="postgres"


[redis]
host="localhost"
port=6379
