APPENV="dev"

[log]
format="json"
level="info"
noColor="no_color"

[app]
httpaddr=4000

[database]
host="localhost"
port=3306
user="viigstar"
pass="12345678"
name="dev"

[redis]
host="localhost"
port=6379
